/// Flutter icons Wishlist
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Wishlist
///      fonts:
///       - asset: fonts/Wishlist.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Wishlist {
  Wishlist._();

  static const _kFontFam = 'Wishlist';
  static const String? _kFontPkg = null;

  static const IconData favorite_border = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
